import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const { content, title } = await req.json()

    // Simple HTML-to-text PDF approach using built-in Node capabilities
    // We'll return a plain text file styled as a document since @react-pdf/renderer
    // needs a React render context. For server-side, we create a proper HTML document.

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title || 'Consulting Agreement'}</title>
  <style>
    body {
      font-family: Georgia, 'Times New Roman', serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 60px 80px;
      line-height: 1.6;
      color: #1a1a1a;
      font-size: 12pt;
    }
    h1, h2, h3 { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111; }
    h1 { font-size: 22pt; border-bottom: 2px solid #111; padding-bottom: 8px; }
    h2 { font-size: 15pt; margin-top: 28px; }
    h3 { font-size: 12pt; margin-top: 20px; }
    p { margin: 10px 0; }
    ul, ol { margin: 10px 0; padding-left: 24px; }
    hr { border: none; border-top: 1px solid #ddd; margin: 24px 0; }
    .footer { margin-top: 60px; border-top: 1px solid #ddd; padding-top: 16px; font-size: 10pt; color: #666; }
    pre { background: #f5f5f5; padding: 12px; font-size: 10pt; white-space: pre-wrap; }
  </style>
</head>
<body>
  ${content
    .split('\n')
    .map((line: string) => {
      if (line.startsWith('# ')) return `<h1>${line.slice(2)}</h1>`
      if (line.startsWith('## ')) return `<h2>${line.slice(3)}</h2>`
      if (line.startsWith('### ')) return `<h3>${line.slice(4)}</h3>`
      if (line.startsWith('- ') || line.startsWith('* ')) return `<li>${line.slice(2)}</li>`
      if (line.trim() === '---') return '<hr>'
      if (line.trim() === '') return '<br>'
      return `<p>${line}</p>`
    })
    .join('\n')}
  <div class="footer">
    <p>Generated by Proposal Builder — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="proposal-${Date.now()}.html"`,
      },
    })
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 })
  }
}
