import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx"
import { NextRequest, NextResponse } from 'next/server'

function toFileName(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return normalized || 'proposal'
}

function buildParagraphs(content: string): Paragraph[] {
  return content.split(/\r?\n/).map((rawLine) => {
    const trimmed = rawLine.trim()

    if (!trimmed || trimmed === '---') {
      return new Paragraph({
        text: '',
        spacing: { after: 160 },
      })
    }

    if (trimmed.startsWith('### ')) {
      return new Paragraph({
        text: trimmed.slice(4),
        heading: HeadingLevel.HEADING_3,
      })
    }

    if (trimmed.startsWith('## ')) {
      return new Paragraph({
        text: trimmed.slice(3),
        heading: HeadingLevel.HEADING_2,
      })
    }

    if (trimmed.startsWith('# ')) {
      return new Paragraph({
        text: trimmed.slice(2),
        heading: HeadingLevel.HEADING_1,
      })
    }

    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      return new Paragraph({
        text: trimmed.slice(2),
        bullet: { level: 0 },
      })
    }

    return new Paragraph({
      children: [new TextRun(trimmed)],
      spacing: { after: 160 },
    })
  })
}

export async function POST(req: NextRequest) {
  try {
    const { content, title } = await req.json()
    const documentTitle = title || 'Consulting Agreement'
    const doc = new Document({
      sections: [
        {
          children: [
            new Paragraph({
              text: documentTitle,
              heading: HeadingLevel.TITLE,
            }),
            ...buildParagraphs(content),
            new Paragraph({
              text: `Generated by Proposal Builder on ${new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}`,
              spacing: { before: 320 },
            }),
          ],
        },
      ],
    })

    const buffer = await Packer.toBuffer(doc)
    const fileName = `${toFileName(documentTitle)}-${Date.now()}.docx`

    return new NextResponse(buffer, {
      headers: {
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${fileName}"`,
      },
    })
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 })
  }
}
